import type { Metadata } from "next";
import { CustomProvider } from 'rsuite';
import 'rsuite/dist/rsuite-no-reset.min.css';
import "./globals.css";
import { AuthContextProvider } from "../context/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomProvider>
          <AuthContextProvider>
            {children}
          </AuthContextProvider>
        </CustomProvider>
      </body>
    </html>
  );
}
